### ISSUE TITLE
HTTP/1 optimisation

### ISSUE THREAD

**Issue by nweldev** [Sedona-Solutions/sdn-angularjs-seed#15]
By default, most projects still use HTTP/1 in production. We therefor need to make, by default, a bundle for the target/dist which will include all the main.js dependencies, including jspm libraries, and bundles for the lazy loaded modules (excluding the dependencies already included in the "main" bundle). 

The "alternatives" to this (HTTP/2 oriented, without any bundle, and HTTP/1 oriented but with separated jspm librairies bundle for a centralized management and cache optimisation) are planned for 1.2.0, and will be covered by another issue, but needs to be anticipated.

**Comment by nweldev** [comment]
gulp/tasks/release seems to already cover this issue. Just check this during the resolution of #18, and close it if no modification was needed, or with the same pull request.

**Comment by SylvainBigonneau** [comment]
Fixed by  #24

**Comment by SylvainBigonneau** [comment]
Here are the unwanted calls:
- ng1.js  
- core.js  
- router.js 
- dashboards.js 
- bower-angular@1.5.5.js  
- Module.js 
- Component.js  
- Directive.js  
- Injectable.js 
- Routes.js

**Comment by nweldev** [comment]
closed by 6033c0915162077253e9249fe78267d735b6287b
